var translate = angular.module("MainApp");

app.config(['$translateProvider', function ($translateProvider) {
    $translateProvider.useSanitizeValueStrategy(null);
    $translateProvider.translations("en", {
        "Active":"Active",
        "Id": "Id",
        "ProductTypeCode": "Code",
        "AddProductType": "Add Product type",
        "MaintenanceProductType": "Product Type Maintenance",
        "CorporationMaintenance": "Corporation Maintenance",
        "AddCorporation": "Add Corporation",
        "CorporationCode": "Corporation Code",
        "CorporationName": "Corporation Name",
        "Corporationcountry": "Country",
        "CorporationRegistry": "Registry",
        "CorporationCostCenter": "Cost Center",
        "CorporationObservation": "Observations",
        "Disable": "Disable",

        "EditProductType": "Edit Product Type",
        "Name": "Name",
        "viewWaggon": "view by containers",
        "AddUser": "Add User",
        "AddWaggons": "Add Containers",
        "SelectAll": "SELECT MARKS AND PRESENTATIONS",
        "MonthlySelectKPI": "Select month",
        "InsertYear": "Insert year",
        "MonthlySelect": "SELECT MONTH",
        "MonthlyKpi": "Monthly",
        "WaggonKpi": "By Waggon",
        "Resume": "Resume",
        "DespKpi": "The following is the details of the fulfillment of the order of the month of",
        "Details": "Details",
        "NoData": "No data",
        "OrdderT": "Order type",
        "ReportKpi": "KPI REPORT",
        "InitialOrd": "Initial Order",
        "Dife": "Difference",
        "Back": "Return",
        "ClaimsHelp": "Claims Policy (Spanish)",
        "ClaimsHelpEN": "Claims Policy (English)",
        "TotalOrder": "Total Order",
        "Compl": "fulfillment",
        "Code": "Code",
        "MonthlyRt": "Month",
        "DescripRt": "Below is the details of fulfillment of the order of the month.",
        "SMRt": "Selected Month:",
        "YearRt": "Year",
        "ViewRt": "View Report",
        "AllMark": "All Mark",
        "AllPresentation": "All Presentation",
        "Consolidated": "Consolidated Monthly",
        "InvoiceReport": "ORDER VS BILLED REPORT",
        "AddOrder": "Add order",
        "AddIma": "ADD",
        "AppName": "Ordering system",
        "Banner": "../../Content/Images/index-bannerEN.png",
        "Boxes": "Boxes",
        "Yes": "Yes",
        "No": "No",
        "Help": "Help",
        "Manualhelp": "HELP MANUAL",
        "App": "ANDROID APP",
        "AppDownload": "DOWNLOAD",
        "Poli": "Privacy policies",
        "AccpetPoli": "I accept",
        "AccpetPr": "Complaints polices",
        "AccpetP": "Policy Order Entry through the Web system.",
        "HelpTitle": "HELP AND SUPPORT SYSTEMA",
        "HelpTitleDescrip": "STORAGE PRODUCT SPECIFICATIONS",
        "DescripHelp": "These are help documents",
        "NameDocument": "DOCUMENT NAME",
        "NamePolices": "POLICY ON USE OF THE WEB",
        "ProductPV": "PRODUCT SPECIFICATIONS OF PETIT VEGETALES 330 ML",
        "ProductEP": "PRODUCT SPECIFICATIONS OF EPAC020 PETIT PLAY 200 ML",
        "ProductDC": "PRODUCT SPECIFICATIONS OF NECTAR PETIT 200, LATA, DC, LITRO NEW STOW",
        "ProductNJ": "PRODUCT SPECIFICATIONS OF NECTAR PETIT JUGAZZO 200 ML COLOMBINA",
        "ProductCP": "PRODUCT SPECIFICATIONS OF COSECHA PURA, LT, 500 ML, DREAM CAP NEW STOW",
        "ProductPL": "PRODUCT SPECIFICATIONS OF PETIT LIGHT 330 ML AND LITERS",
        "Download": "Download",
        "Save": "Save",
        "ChagePass": "Change",
        "Concurret": "Concurrent Password",
        "NewPass": "New Password",
        "ConfirmPass": "Confirm Password",
        "DetallePass": "Modify your password",
        "Setting": "Setting",
        "imagepro": "Image",
        "EditPass": "Edit Password",
        "EditImage": "Change Image",
        "DataDescription": "Data Description",
        "Zoom": "Zoom in graph",
        "TypeProduct": "Product Type",
        "All": "All",
        "TotalFPedidos": "Total Container Order",
        "TotalETiempo": "Total sent on time",
        "PorcentajeCumpl": "percentage of compliance",
        "TCP": "Total Boxes Orders",
        "TCE": "Total Boxes Sent",
        "TLP": "Total Lines Orders",
        "TC": "Total complete",
        "LNC": "Unfulfilled lines",
        "RDI": "Reasons for failure",
        "DateCreateR": "Creation Date",
        "DateOrderR": "Order Date",
        "DateBillerR": "Invoicing Date",
        "EstadoR": "Status",
        "Motivo": "Reason for lead/lag",
        "ProductR": "Product",
        "InvoicedR": "Invoiced",
        "SKUMotivo": "SKU Reason",
        "MSJNoOrders": "There is no order placed for this month.",
        "ComentarioIndicadores": "Comment on indicators",
        "OrderRep": "Order",
        "OrderTable": "Order",
        "TitleKpiMonthlyDetail": "KPI DETAIL OF COMPLIANCE ORDERS",
        "BoxesQty": "Boxes per pallet",
        "Cancel": "Cancel",
        "capacity": "Capacity",
        "showAll": "Show All",
        "hideAll": "Hide All",
        "Client": "Client",
        "ClientCode": "Client code",
        "Apply": "Apply",
        "CodePreimpreso": "Preprinted Code",
        "ConfirmRemove": "Are you sure you want to remove this order?",
        "Completed": "Complete",
        "CompletedWaggons": "Completed",
        "SquareSomeApply": "Some Apply",
        "Contacts": "Contacts",
        "ContactUs": "Contact Us",
        "CorrelativePO": "P.O. Customer",
        //"CreationDate": "Creation date"
        "CreationDate": "Created on",
        "DuplicateWaggon": "Duplicate Container",
        "EndDate": "End date",
        "English": "English",
        "Date": "Date:",
        "Invoi": "Invoice:",
        "ExtraOrder": "Extra order",
        "globalOrderDelail": "Global Order Detail",
        "GlobalSummary": "Global summary",
        "Incomplete": "Incomplete",
        "IncompleteWaggons": "Incomplete",
        "InProcess": "In process",
        "Invoiced": "billed",
        "SquareAllApply": "All Qualifies",
        "SquarePending": "Pending",
        "SquareNoneApplies": "None Applies",
        "Languages": "Languages",
        "Login": "Log in",
        "Maintenainces": "Maintenances",
        "MaquilaClient": "Maquila Custumer",
        "MaquilaDetail": "Maquila summary",
        "maquilaProduct": "Maquila Product",
        "MaquilaSummary": "Maquila Summary",
        "ModifyOrder": "Modify order",
        "Month": "Month",
        "Claims":"Complaints",
        "MonthlyOrders": "Monthly orders",
        "MonthlyExtraOrders": "Monthly extra orders",
        "More": "More",
        "NewOrder": "New order",
        "NewClaims": "NEW CLAIM",
        "Consult": "Check",
        "NoCommentaries": "No commentaries",
        "Ok": "Accept",
        "Order": "Order",
        "OrderAuthorize": "Autorization of orders",
        "Orders": "Orders",
        "OrderSelectParagraph": "Select an order to set containers.",
        "OrderSheet": "Order sheet",
        //"OrderStatus": "Order status",
        "OrderStatus": "Status",
        "OrderSummary": "Order summary",
        "OrdersToAdd": "How many orders do you want to add?",
        "OwnClient": "Own customer",
        "Owndetail": "Own Summary",
        "ownProduct": "Nectar",//"Own product",
        "OwnSummary": "Nectar summary",
        "Password": "Password",
        "PasswordPlaceHolder": "Type your password",
        "Platforms": "pallet",
        "PricePerPlatform": "Price per pallet",
        "PricePerBox": "Price per pallet",
        "QtyTarBoxes": "Pallet/Boxes",
        "RememberMe": "Remember me",
        "RemoveOrder": "Remove Order",
        "ReportOrder": "Ordered vs billed",
        "ReportOrderTime": "On time delivery",
        "Rest": "Rest",
        "Return": "Return",
        "SearchByUser": "Search by User",
        "SearchOrder": "Search order",
        "InitialDate": "Initial Date:",
        //"EndDate": "End Date:",
        "SearchOrderMonthly": "SEARCH MONTHLY ORDER",
        "SearchOrderWaggon": "SEARCH CONTAINER ORDER",
        "InformationComplaints": "INFORMATION COMPLAINTS",
        "SelectAWaggon": "Select a container",
        "SelectOption": "---Select an option---",
        "ShipDate": "Ship date",
        "DateReporting": "Reporting Date To Beliv:",
        "DateFormat": "Ship Date Format:",
        "PersonSendClaim": "Person Sending The Claim",
        "Conductor": "Driver",
        "Marca": "Mark",
        "Tamano": "Size",
        "Sabor": "Flavor",
        "Profile": "PROFILE",
        "ProfileImage": "Select an picture",
        "MessageComplaint": "¡This Claim is complete!",
        "MessageComplaint2": "Sent a response to your email",
        //"Yes": "Yes",
        "Not": "Not",
        "Unit": "Unit",
        "Box": "Box",
        "Pallet": "Pallet",
        "Unidades": "Units",
        "Cajas": "Boxes",
        "Defecto": "Defect",
        "Fotografia": "Photographs",
        "Cantidad": "Quantity",
        "Muestra": "Sample",
        "UnitaryPrice": "Unitary Price",
        "ProductCode": "Product Code",
        "Add": "Add",
        "Direction": "Direction",
        "TotaAmount": "Total",
        "TotaClaimed": "Total claimed",
        "TransportCompany": "Transport Company",
        "NumberInvoice": "Number Invoice",
        "SaleDefinition": "Sale Definition",
        "Next": "Next",
        //"ShipmentDate": "Shipment date",
        "ShipmentDate": "Applied for",
        "ShippingDetail": "Shipping detail",
        "Spanish": "Spanish",
        "Start": "Start",
        "StartDate": "Start date",
        "StartSession": "Log in",
        "Summary": "Summary",
        "transportType": "Transportation type",
        "UpdateCatalogs": "Update SAP catalogs",
        "User": "User",
        "DescripInfoClient": "CUSTOMER INFORMATION",
        "DescripInfoProduct": "PRODUCT INFORMATION",
        "DescripStep1": "STEP 1",
        "DescripStep2": "STEP 2",
        "DescripStep3": "STEP 3",
        "DescripStep4": "STEP 4",
        "DescripImage": "Images",
        "DescripReclamoClient": "Complaint description",
        "AddImage": "ADD IMAGE",
        "UserAlreadyExist": "User Already exist!",
        "UserPlaceHolder": "Type your user",
        "WaggonExtraOrders": "Container extra order",
        "WaggonOrders": "Container order",
        "WaggonsQty": "Containers quantity",
        "Qty":"Quantity",
        "WaggonsToDispatch": "To dispatch",
        "WebOrder": "Web Order",
        "Pais": "Country / Consumer Address:",
        //"Details": "Details",
        "WelcomeTo": "Welcome to the",
        "Together": "Together we go further",
        "EnterCredentials": "enter your username and password",
        "Preimpreso": "Preprinted",
        "ProgramationDate": "Ships in",
        "DispatchDate": "Real dispatch date",
        "BLNumber": "Bl number",
        //"TransportCompany": "Transport company",
        "ETA": "Programmed to",
        "ETD": "Ships in",
        "SAPNumber": "SAP Number",
        //description text
        "SelectDetails": "Select to see detail.",
        "SelectOrder": "Choose the order type you want.",
        "MonthlyProductDetail": "Here it shows you the details of your current order.",
        "MonthlyOrderPerMonth": "Here it shows you the orders from ",
        "MonthlyOrderList": 'Here it shows you the active monthly orders. Please select "New Order" for ordering or select an order to view the detail.',
        'ParagraphOrderSheet': "Select products from the following catalog.",
        "ParagraphNewWaggonOrder": "Please enter the number of orders you want.",
        "DuplicateOrAddWaggon": "Duplicate or add a new container",
        "ParagraphSelectQueryType": "Select the type of order you want to check.",
        "ParagraphSearchResult": "The results of your search are shown.",
        "ParagraphOrdersToAdd": "Please enter the number of order you want to add.",
        "ParagrephWaggongToImport": "Choose the container to import.",
        "UnAuthorized": "You have not authorization to do an extra order, Please contact your billing and export executive of Livsmart!",
        "ParagaphWaggonShipped": "Here is your order's shipping detail from ",

        //Status
        'En espera': 'Waiting',
        'En proceso': 'In process',
        'Facturado': 'Invoiced',

        //'Tamaño de transporte'
        '20 PIES': '20 ft',
        '22 PIES': '22 ft',
        '40 PIES': '40 ft',
        '43 PIES': '43 ft',
        '45 PIES': '45 ft',
        '46 PIES': '46 ft',
        '48 PIES': '48 ft',
        'FURGON': 'WAGGON',
        'CONTENEDOR': 'CONTAINER',

        'MaintenancesExce': 'Excellence Maintenance',
        'Excellence': 'Excellence program',

        //'Notas de credito'
        'creditNotes': 'Credit Notes',
        'title': 'Credit Notes',
        'selectType': 'Type',
        'select': '--- Select type ---',
        'contact': 'Contact',
        'selectDate': 'Date',
        'selectCoin': 'Coin',
        'selectC': '--- Select coin ---',
        'numFact': 'Invoice number',
        'details': 'Details',
        'code': 'UMS code',
        'quantity': 'Quantity',
        'priceU': 'Unit price',
        'btn': 'Save',
        'btn1':'Add',
        'closed':'Closed',
        'Sfrom': 'From',
        'Sto': 'To',
        'Syear': 'Year',
        'new': 'Add',
        'invoice': 'Invoice',
        'numberCN': 'gestion number',
        'btnSearch': 'Search',
        'selectStates': 'Status',
        'correlative': 'Correlative',
        'email': 'Email',
        'resolutionDate': 'Invoice Date',
        'userRes': 'User resolution',
        'realRate': 'Real exchanged rate',
        'agreedRate': 'Agreed exchanged rate',
        'months': 'Month',
        'creditNotesNumber': 'Credit note number',
        'description': 'Description',

        //currencies
        'currencies': 'Currencies',
        'titleC': 'Currency maintenance',
        'codeC': 'Code',
        'country': 'Country',
        'symbol': 'Symbol',
        'selectCountry': '--- Select country ---',

        //exchange
        'titleE': 'Rate maintenance',
        'exchange': 'Rate',
        'selectCurrencies': 'Currencies',
        'rate': 'Rate',

        //proyeccion de compras
        'purchaseProjection': 'Purchase Projections',
        purchaseProjectionParagraph:'Here it shows you the orders projected for the next months'

    });

    $translateProvider.translations("es", {
        "Active": "Activo",
        "AddProductType": "Agregar tipo de producto",
        "MaintenanceProductType": "Mantenimiento de Tipos de Productos",
        "CorporationMaintenance": "Mantenimiento de sociedades",
        "AddCorporation": "Agregar sociedad",
        "EditProductType": "Editar Tipo de Producto",
        "CorporationCode": "Código sociedad",
        "CorporationName": "Nombre sociedad",
        "Corporationcountry": "Pais",
        "CorporationRegistry": "Numero de Registro",
        "CorporationCostCenter": "Centro",
        "CorporationObservation": "Observaciones",
        "Disable": "Deshabilitar",
        "viewWaggon": "Ver en furgones",
        "AddUser": "Agregar usuario",
        "AddWaggons": "Agregar furgones",
        "AddOrder": "Agregar pedido",
        "Consolidated": "Consolidado Mensual",
        "DescripRt": "A continuación se le muestra los detalles de cumplimiento del pedido del mes.",
        "SMRt": "Mes Seleccionado:",
        "InsertYear": "Ingrese año",
        "WaggonKpi": "Por furgon",
        "Details": "Detalles",
        "DespKpi": "A continuación se le muestra los detalles de cumplimito del pedido del mes de",
        "MonthlyKpi": "Mensual",
        "ReportKpi": "REPORTE DE KPI",
        "OrdderT": "Tipo de pedido",
        "NoData": "No hay datos:",
        "InitialOrd": "Pedido Inicial",
        "Dife": "Diferencia",
        "Resume": "Resumen",
        "ClaimsHelp": "Politicas de reclamos",
        "ClaimsHelpEN": "Politicas de reclamos (Ingles)",
        "Code": "Código",
        "Back": "Regresar",
        "Compl": "Cumplimiento",
        "TotalOrder": "Pedido Total",
        //"InitialOrd": "Pedido Inicial",
        "SelectAll": "SELECCIONE MARCAS Y PRESENTACIONES",
        "MonthlySelect": "SELECCIONE MES",
        "MonthlySelectKPI": "Seleccione mes",
        "MonthlyRt": "Mes",
        "YearRt": "Año",
        "ViewRt": "Ver Reporte",
        "AllMark": "Todas las marcas",
        "AllPresentation": "Todas las Presentaciones",
        "InvoiceReport": "REPORTE DE PEDIDO VS FACTURADO",
        "AddIma": "AGREGAR",
        'Amount': "Monto",
        "AppName": "Sistema de gestión de pedidos",
        "Banner": "../../Content/Images/index-banner.png",
        "Boxes": "Cajas",
        "BoxesQty": "Cajas por tarima",
        "Cancel": "Cancelar",
        "CancelOrder": "Cancelar pedido",
        "showAll": "Mostrar todos",
        "hideAll": "Ocultar todos",
        "capacity": "Capacidad",
        "Claims": "Reclamos",
        "Clear": "Borrar",
        "Client": "Cliente",
        "Manualhelp": "MANUAL DE AYUDA",
        "ClientCode": "Código de cliente",
        "Close": "Cerrar",
        "CodePreimpreso": "Código preimpreso",
        //"Code": "Código",
        "ConfirmRemove": "¿Está seguro que desea eliminar este pedido?",
        "Commentary": "Comentario",
        "Comments": "Comentarios",
        "Completed": "Completo",
        "CompletedWaggons": "Completos",
        "SquareSomeApply": "Algunos Aplican",
        "Consult": "Consultar",
        "Contacts": "Contactos",
        "ContactUs": "Contactenos",
        "CorrelativeClientCode": "Código correlativo cliente",
        "CorrelativePO": "P.O. Cliente",
        //"CreationDate": "Fecha de creación",
        "CreationDate": "Creado el",
        "Delete": "Borrar",
        "Deleted": "Eliminado",
        "Duplicate": "Duplicar",
        "DuplicateWaggon": "Duplicar furgón",
        "EndDate": "Fecha de fin",
        "English": "Ingles",
        "Yes": "Si",
        "No": "No",
        "Help": "Ayuda",
        "App": "APP ANDROID",
        "AppDownload": "DESCARGAR",
        "Poli": "Póliticas de Privacidad",
        "AccpetPoli": "Acepto las",
        "AccpetPr": "Póliticas de reclamos",
        "AccpetP": "Políticas de Ingreso de Pedidos a través del sistema Web",
        "HelpTitle": "AYUDA Y SOPORTE DEL SISTEMA",
        "HelpTitleDescrip": "ESPECIFICACIONES DE ALMACENAJE DE PRODUCTOS",
        "DescripHelp": "A continuación se muestran los documentos de ayuda",
        "NameDocument": "NOMBRE DOCUMENTO",
        "NamePolices": "POLITICAS DE USO DE LA WEB",
        "ProductPV": "ESPECIFICACIONES DE PRODUCTO PETIT VEGETALES 330 ML",
        "ProductEP": "ESPECIFICACIONES DE PRODUCTO EPAC020 PETIT PLAY 200 ML",
        "ProductDC": "ESPECIFICACIONES DE PRODUCTO NECTAR PETIT 200, LATA, DC, LITRO NUEVOS ESTIBADOS",
        "ProductNJ": "ESPECIFICACIONES DE PRODUCTO NECTAR PETIT JUGAZZO 200 ML COLOMBINA",
        "ProductCP": "ESPECIFICACIONES DE PRODUCTO COSECHA PURA, LT, 500 ML, DREAM CAP NUEVO ESTIBADO",
        "ProductPL": "ESPECIFICACIONES DE PRODUCTO PETIT LIGHT 330 ML Y LITRO",
        "Download": "Descargar",
        "ChagePass": "Cambiar",
        "Concurret": "Clave actual",
        "NewPass": "Nueva clave",
        "ConfirmPass": "Confirmar clave",
        "DetallePass": "Modifique su clave",
        "Setting": "Configuración",
        "EditPass": "Cambiar Clave",
        "EditImage": "Cambiar Image",
        "DataDescription": "Descripción de Datos",
        "Zoom": "Ampliar Gráfica",
        "All": "Todos",
        "TypeProduct": "Tipo Producto",
        "TotalFPedidos": "Total Furgones Pedido",
        "TotalETiempo": "Total enviados a tiempo",
        "PorcentajeCumpl": "Porcentaje de Cumplimiento",
        "TCP": "Total Cajas Pedidas",
        "TCE": "Total Cajas Enviadas",
        "TLP": "Total Lineas Pedidas",
        "TC": "Total Cumplidas",
        "LNC": "Lineas No Cumplidas",
        "RDI": "Razones de incumplimiento",
        "DateCreateR": "Fecha de Creación",
        "DateOrderR": "Fecha de Pedido",
        "DateBillerR": "Fecha de Facturación",
        "EstadoR": "Estado",
        "Motivo": "Motivo de adelanto/atraso",
        "ProductR": "Producto",
        "InvoicedR": "Facturado",
        "SKUMotivo": "Motivos SKU",
        "MSJNoOrders": "No hay ningun pedido realizado para este mes.",
        "ComentarioIndicadores": "Comentario sobre indicadores",
        "OrderRep": "Pedido",
        "OrderTable": "Orden",
        "Line": "Linea",
        "TitleKpiMonthlyDetail": "KPI DETALLE DE CUMPLIMIENTO DE PEDIDOS",
        "ParagraphKpiMonthlyDetail": "A continuación se le muestra los detalles de cumplimiento del pedido del mes de",
        "ExtraOrder": "Pedido extra",
        "globalOrderDelail": "Detalle global de pedido",
        "GlobalSummary": "Total global",
        "Import": "Importar",
        "Incomplete": "Incompleto",
        "IncompleteWaggons": "Incompletos",
        "SquarePending": "Pendientes",
        "SquareNoneApplies": "Ninguno Aplica",
        "InProcess": "En proceso",
        "Invoiced": "Facturado",
        "SquareAllApply": "Todos Aplican",
        "Languages": "Idiomas",
        "Login": "Ingresar",
        "Maintenances": "Mantenimientos",
        "MaquilaClient": "Cliente maquila",
        "MaquilaDetail": "Detalle maquila",
        "maquilaProduct": "Producto maquila",
        "MaquilaSummary": "Total maquila",
        "Modify": "Modificar",
        "ModifyOrder": "Modificar pedido",
        "Month": "Mes",
        "MonthlyOrders": "Pedidos mensuales",
        "MonthlyExtraOrders": "Pedido extra mensual",
        "More": "Más",
        "NewOrder": "Nuevo pedido",
        "NewClaims": "NUEVO RECLAMO",
        "NoCommentaries": "No hay comentarios",
        "Ok": "Aceptar",
        "Order": "Pedido",
        "OrderAuthorize": "Autorización para creación de pedidos",
        "OrderDate": "Fecha de pedido",
        "Orders": "Pedidos",
        "OrderSelectParagraph": "Selecciona un pedido para ingresar furgones.",
        "OrderSheet": "Hoja de pedido",
        //"OrderStatus": "Estado del pedido",
        "OrderStatus": "Status",
        "OrderSummary": "Detalle pedido",
        "OrdersToAdd": "¿Cuantos pedidos deseas agregar?",
        "OwnClient": "Cliente propio",
        "OwnDetail": "Detalle nectar",
        "ownProduct": "Nectar",// "Producto propio",
        "OwnSummary": "Total nectar",
        "Password": "Contraseña",
        "PasswordPlaceHolder": "Ingresa tu contraseña",
        "Platforms": "Tarimas",
        "Price": "Precio",
        "PricePerPlatform": "Precio por tarima",
        "PricePerBox" :"Precio por caja",
        "Print": "Imprimir",
        "Product": "Producto",
        "ProductCode": "Código de producto",
        "Qty": "Cantidad",
        "QtyTarBoxes": "Tarimas/Cajas",
        "RememberMe": "Recordar sesión",
        "RemoveOrder": "Borrar pedido",
        "Reports": "Reportes",
        "ReportOrder": "Reporte de pedido vs facturado",
        "ReportOrderTime": "Reporte de pedidos a tiempo",
        "Result": "Resultado",
        "Rest": "Restante",
        "Return": "Regresar",
        "Save": "Guardar",
        "Search": "Buscar",
        "Date": "Fecha:",
        "Invoi": "Factura:",
        "SearchByUser": "Buscar por usuario",
        "SearchOrder": "Buscar pedido",
        "InitialDate": "Fecha Inicial",
        //"EndDate": "Fecha Final:",
        "SearchOrderMonthly": "BUSQUEDA PEDIDO MENSUAL",
        "SearchOrderWaggon": "BUSQUEDA PEDIDO POR FURGON",
        "SelectAWaggon": "Seleccione un furgón",
        "SelectOption": "---Selecciona una opción ---",
        "Name": "Nombre",
        "ProductTypeCode":"Código",
        "Send": "Enviar",
        "ShipDate": "Fecha de despacho",
        "DateReporting": "Fecha de reporte a Beliv",
        "DateFormat": "Fecha de envio formato",
        "PersonSendClaim": "Persona que envio el reclamo",
        "Conductor": "Conductor",
        "TransportCompany": "Compañia de Transporte",
        "NumberInvoice": "Número de factura",
        "SaleDefinition": "Termino de venta",
        "Next": "Siguiente",
        //"ShipmentDate": "Fecha de envío",
        "ShipmentDate": "Solicitado para",
        "ShippingDetail":"Detalle de envío",
        "Spanish": "Español",
        "Start": "Inicio",
        "StartDate": "Fecha de inicio",
        "StartSession": "Iniciar sesión",
        "SubSummary": "Subtotal",
        "Summary": "Total",
        "Today": "Hoy",
        "Transport": "Transporte",
        "transportType": "Tipo de transporte",
        "Trucks": "Furgones",
        "UpdateCatalogs": "Actualización de catálogos SAP",
        "User": "Usuario",
        "DescripInfoClient": "INFORMACION DEL CLIENTE",
        "DescripInfoProduct": "INFORMACION DEL PRODUCTO",
        "DescripStep1": "PASO 1",
        "DescripStep2": "PASO 2",
        "DescripStep3": "PASO 3",
        "DescripStep4": "PASO 4",
        "DescripImage": "Imagenes",
        "imagepro": "Imagen",
        "DescripReclamoClient": "Descripción del reclamo",
        "UserAlreadyExist": "El nombre de usuario ya esta en uso.",
        "UserMaintenaince": "Mantenimiento de usuarios",
        "UserPlaceHolder": "Ingresa tu usuario",
        "WaggonExtraOrders": "Pedido extra por furgones",
        "WaggonOrders": "Pedido por furgon",
        "WaggonsQty": "Número de furgones",
        "WaggonsToDispatch": "A despachar",
        "WebOrder": "Pedido web",
        "Pais": "País / Dirección del consumidor",
        "Marca": "Marca",
        "Tamano": "Tamaño",
        "Sabor": "Sabor",
        "Apply": "Aplica",
        "Profile": "PERFIL",
        "ProfileImage": "Seleccione una imagen",
        "MessageComplaint": "¡Este Reclamo se ha completado!", 
        "MessageComplaint2": "Se le ha enviado a su correo Electronico los detalles de la respuesta",
        //"Yes": "Si",
        "Not": "No",
        "Unit": "Unidad",
        "Box": "Caja",
        "Pallet": "Tarimas",
        "Defecto": "Defecto",
        "Muestra": "Muestra",
        "Fotografia": "Fotografia",
        "Cantidad": "Cantidad",
        "UnitaryPrice": "Precio Unitario",
        //"ProductCode": "Código Producto",
        "Add": "Agregar",
        //"Details": "Detalles",
        "TotaAmount": "Total",
        "TotaClaimed": "Total reclamado",
        "Direction": "Dirección",
        "InformationComplaints": "INFORMACION DEL RECLAMO",
        "AddImage": "AGREGAR IMAGEN",
        "WelcomeTo": "Bienvenido al",
        "Welcome": "Bienvenido",
        "Together": "Juntos llegamos más lejos",      
        "EnterCredentials":"ingresa tu usuario y tu contraseña",
        "Preimpreso": "Preimpreso",
        "ProgramationDate": "Fecha de programación",
        "DispatchDate": "Despachado el",
        "BLNumber": "Número BL",
        //"TransportCompany": "Compañia de transporte",
        "ETA": "Programado para",
        "ETD": "Despachado el",
        "SAPNumber": "Número SAP",

        //description text
        "SelectDetails": "Seleccione para ver el detalle.",
        "SelectOrder": "Seleccione el tipo de pedido que desea realizar.",
        "MonthlyProductDetail": "A continuación se le muestra los detalles de su pedido actual.",
        "MonthlyOrderPerMonth": "A continuación se le muestran los pedidos de ",
        "MonthlyOrderList": 'A continuación se muestra el listado de pedidos mensuales activos. Por favor seleccione "Nuevo Pedido" para hacer un pedido o seleccione un pedido para ingresar al detalle.',
        'ParagraphOrderSheet': "Seleccione los productos del siguiente catalogo.",
        "ParagraphNewWaggonOrder": "Por favor ingrese el número de pedidos que desea realizar.",
        "DuplicateOrAddWaggon": "Duplique o agregue un nuevo furgón",
        "ParagraphSelectQueryType": "Seleccione el tipo de pedido de consulta  que desea realizar.",
        "ParagraphSearchResult": "A continuación se muestran los resultados de su busqueda.",
        "ParagraphOrdersToAdd": "Por favor ingrese el numero de pedidos que desea agregar.",
        "ParagrephWaggongToImport": "Seleccione el furgón que desea importar.",
        "UnAuthorized": "No tiene autorizacion para realizar pedidos extras, favor comuniquese con su ejecutivo de facturación y exportacion de livsmart!",
        "ParagaphWaggonShipped": "A continuación se le muestra el detalle de envío de su pedido mensual de ",
        'MaintenancesExce': 'Mantenimiento excelencia',
        'Excellence': 'Programa de excelencia',

        //'Notas de credito'
        'creditNotes': 'Notas de credito',
        'title': 'Notas de Credito',
        'selectType': 'Tipo',
        'select': '--- Seleccione tipo ---',
        'contact': 'Contacto',
        'selectDate': 'Fecha',
        'selectCoin': 'Moneda',
        'selectC': '--- Seleccione moneda ---',
        'numFact': 'Número de factura',
        'details': 'Detalles',
        'code': 'Código UMS',
        'quantity': 'Cantidad',
        'priceU': 'Precio unitario',
        'btn': 'Guardar',
        'btn1': 'Agregar',
        'closed': 'Cerradas',
        'Sfrom': 'Desde',
        'Sto': 'Hasta',
        'Syear': 'Año',
        'new': 'Agregar',
        'invoice': 'Factura',
        'numberCN': 'Numero de gestion',
        'btnSearch': 'Buscar',
        'selectStates': 'Estatus',
        'correlative': 'Correlativo',
        'email': 'Correo',
        'resolutionDate': 'Fecha de la factura',
        'userRes': 'Usuario de resolución',
        'realRate': 'Tasa de cambio real',
        'agreedRate': 'Tasa de cambio convenida',
        'months': 'Mes',
        'creditNotesNumber': 'Número de nota de credito',
        'description':'Descripción',

        //currencies
        'currencies':'Monedas',
        'titleC': 'Mantenimiento de monedas',
        'codeC': 'Código',
        'country': 'Pais',
        'symbol': 'Simbolo',
        'selectCountry': '--- Seleccione pais ---',

        //exchange
        'titleE': 'Mantenimiento de tasa',
        'exchange': 'Tasa',
        'selectCurrencies': 'Monedas',
        'rate': 'Tasa',
        //proyeccion de compras
        'purchaseProjection': 'Proyecciones de compra',
        purchaseProjectionParagraph: 'A continuacion encontrara la proyecciones de compras para los proximos meses'

    });

    $translateProvider.preferredLanguage('es');
}]);
app.service("translateService", [
    "$rootScope", "$translate", "localStorageService", "unitOfWork", "amMoment",
    function ($rootScope, $translate, localStorageService, unitOfWork, amMoment) {
        function changeLanguage(key, setToServer) {
            $translate.use(key);
            localStorageService.set("languageKey", key);
            $rootScope.languageKey = key;
            moment.locale($rootScope.languageKey);

            if ($rootScope.user && setToServer)
                unitOfWork.Language.complexPost(['SetLanguage', key]);
        }

        function selectLanguage() {
            var key = localStorageService.get("languageKey");
            $rootScope.languageKey = key ? key : "es";
            moment.locale($rootScope.languageKey);

            if (!key) return;

            $translate.use(key);
        }
        $rootScope.changeToEnglish = function () {
            changeLanguage("en", true);
        };
        $rootScope.changeToSpanish = function () {
            changeLanguage("es", true);
            moment.locale($rootScope.languageKey);

        };

        this.selectLanguage = selectLanguage;
    }
]);